# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8868791d3fa31aeb9f7ac79b1fac0bc4cace1391983198bf5ec37f15a672274404e260e7ee9fdc3c66f7d2a71cc5cb5f381a11241627ade42fd55939dd586e

test:
  secret_key_base: 5daa6314b8bd5508fe8f9ea55d19387acf63445331cc3fe064330b7552f47b74c1b790cca57a029357cb578a3e2b2f8a01e4fe146c722bd7e014943d050516e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
